name: Validate Katacoda
on: push
jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:

# Setup environment
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: show-environment
      name: Show environment
      run: |
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        echo github.workspace: ${{ github.workspace }}        

# Validate All Scenarios
    - id: install-katacoda-cli
      name: Install Katacoda CLI
      run: |
        sudo npm i katacoda-cli --global
    - id: validate
      name: Validate Katacoda scenarios
      run: |
        katacoda validate:all --repo ${{ github.workspace }}
      continue-on-error: true

# Lint
    - id: lint-code-base
      name: Lint Code Base
      uses: docker://github/super-linter:v3.3.2
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_XML: true
        VALIDATE_MD: true
        VALIDATE_BASH: true
        VALIDATE_PYTHON: false
        VALIDATE_RUBY: false
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_DOCKER: true
        VALIDATE_CSS: true
        VALIDATE_ENV: true
      continue-on-error: true

# Grammer and spell check
